version: '3'

services:
  demo-service:
    container_name: demo-service-py
    image: prambudi/demo-service-py:0.0.1
    env_file:
      - ./resources/.env
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app